#FROM quay.io/fedora/python-39
FROM python:3.11-slim

WORKDIR /app

RUN pip3 install --prefer-binary --extra-index-url https://repo.fury.io/mgiessing chromadb transformers psutil langchain sentence_transformers gradio==3.50.2 openai einops

COPY . /app

EXPOSE 7680

# Run the app
CMD ["python3", "run_model_docker.py"]

