techzone:
  hosts:
    localhost:
  vars:
    ansible_user: username # ssh-login user
    auto_start: true # whether the rag-demo should immediately start serving
    demo_port: 7860 # the http port on which the demo is served.
    python_version: 3.11 # use 3.11 for compatability 
    micromamba_location: "/usr/local/bin/micromamba" # should be in $PATH, otherwise manual intervention required.
    working_directory: "/home/{{ ansible_user }}/rag_demo"
    conda_dir: "/home/{{ ansible_user }}/micromamba" # conda root prefix
    model_repository: "bartowski/ibm-granite_granite-3.2-8b-instruct-GGUF" # huggingface model repository
    model_name: "ibm-granite_granite-3.2-8b-instruct-Q4_K_M.gguf" # gguf file of the model in the repo.
